spring:
  datasource:
    url: jdbc:mysql://localhost:3306/download_upload
    username: devkevin
    password: Teste123@!
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: /home/devkevin/Desktop/ProjectsKevin/Java/DownloadAndUpload/downloadandupload/UploadDir